// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: models/orderbook.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Orderbook struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Symbol            string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Buy               []*MatchEngineEntry    `protobuf:"bytes,2,rep,name=buy,proto3" json:"buy,omitempty"`
	Sell              []*MatchEngineEntry    `protobuf:"bytes,3,rep,name=sell,proto3" json:"sell,omitempty"`
	ConditionalOrders []*Order               `protobuf:"bytes,4,rep,name=ConditionalOrders,proto3" json:"ConditionalOrders,omitempty"`
	Seq               uint64                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Orderbook) Reset() {
	*x = Orderbook{}
	mi := &file_models_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orderbook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orderbook) ProtoMessage() {}

func (x *Orderbook) ProtoReflect() protoreflect.Message {
	mi := &file_models_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orderbook.ProtoReflect.Descriptor instead.
func (*Orderbook) Descriptor() ([]byte, []int) {
	return file_models_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *Orderbook) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Orderbook) GetBuy() []*MatchEngineEntry {
	if x != nil {
		return x.Buy
	}
	return nil
}

func (x *Orderbook) GetSell() []*MatchEngineEntry {
	if x != nil {
		return x.Sell
	}
	return nil
}

func (x *Orderbook) GetConditionalOrders() []*Order {
	if x != nil {
		return x.ConditionalOrders
	}
	return nil
}

func (x *Orderbook) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type MatchEngineEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEngineEntry) Reset() {
	*x = MatchEngineEntry{}
	mi := &file_models_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEngineEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEngineEntry) ProtoMessage() {}

func (x *MatchEngineEntry) ProtoReflect() protoreflect.Message {
	mi := &file_models_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEngineEntry.ProtoReflect.Descriptor instead.
func (*MatchEngineEntry) Descriptor() ([]byte, []int) {
	return file_models_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *MatchEngineEntry) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *MatchEngineEntry) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Volume        string                 `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	TriggerPrice  string                 `protobuf:"bytes,7,opt,name=trigger_price,json=triggerPrice,proto3" json:"trigger_price,omitempty"`
	UserId        int64                  `protobuf:"varint,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TimeInForce   string                 `protobuf:"bytes,9,opt,name=time_in_force,json=timeInForce,proto3" json:"time_in_force,omitempty"`
	Stp           string                 `protobuf:"bytes,10,opt,name=stp,proto3" json:"stp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_models_orderbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_models_orderbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_models_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

func (x *Order) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Order) GetTriggerPrice() string {
	if x != nil {
		return x.TriggerPrice
	}
	return ""
}

func (x *Order) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Order) GetTimeInForce() string {
	if x != nil {
		return x.TimeInForce
	}
	return ""
}

func (x *Order) GetStp() string {
	if x != nil {
		return x.Stp
	}
	return ""
}

var File_models_orderbook_proto protoreflect.FileDescriptor

const file_models_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x16models/orderbook.proto\x12\x06models\"\xcc\x01\n" +
	"\tOrderbook\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12*\n" +
	"\x03buy\x18\x02 \x03(\v2\x18.models.MatchEngineEntryR\x03buy\x12,\n" +
	"\x04sell\x18\x03 \x03(\v2\x18.models.MatchEngineEntryR\x04sell\x12;\n" +
	"\x11ConditionalOrders\x18\x04 \x03(\v2\r.models.OrderR\x11ConditionalOrders\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\"O\n" +
	"\x10MatchEngineEntry\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12%\n" +
	"\x06orders\x18\x02 \x03(\v2\r.models.OrderR\x06orders\"\xf9\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\tR\x06volume\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12#\n" +
	"\rtrigger_price\x18\a \x01(\tR\ftriggerPrice\x12\x17\n" +
	"\auser_id\x18\b \x01(\x03R\x06userId\x12\"\n" +
	"\rtime_in_force\x18\t \x01(\tR\vtimeInForce\x12\x10\n" +
	"\x03stp\x18\n" +
	" \x01(\tR\x03stpB\n" +
	"Z\b./modelsb\x06proto3"

var (
	file_models_orderbook_proto_rawDescOnce sync.Once
	file_models_orderbook_proto_rawDescData []byte
)

func file_models_orderbook_proto_rawDescGZIP() []byte {
	file_models_orderbook_proto_rawDescOnce.Do(func() {
		file_models_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_orderbook_proto_rawDesc), len(file_models_orderbook_proto_rawDesc)))
	})
	return file_models_orderbook_proto_rawDescData
}

var file_models_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_models_orderbook_proto_goTypes = []any{
	(*Orderbook)(nil),        // 0: models.Orderbook
	(*MatchEngineEntry)(nil), // 1: models.MatchEngineEntry
	(*Order)(nil),            // 2: models.Order
}
var file_models_orderbook_proto_depIdxs = []int32{
	1, // 0: models.Orderbook.buy:type_name -> models.MatchEngineEntry
	1, // 1: models.Orderbook.sell:type_name -> models.MatchEngineEntry
	2, // 2: models.Orderbook.ConditionalOrders:type_name -> models.Order
	2, // 3: models.MatchEngineEntry.orders:type_name -> models.Order
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_models_orderbook_proto_init() }
func file_models_orderbook_proto_init() {
	if File_models_orderbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_orderbook_proto_rawDesc), len(file_models_orderbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_orderbook_proto_goTypes,
		DependencyIndexes: file_models_orderbook_proto_depIdxs,
		MessageInfos:      file_models_orderbook_proto_msgTypes,
	}.Build()
	File_models_orderbook_proto = out.File
	file_models_orderbook_proto_goTypes = nil
	file_models_orderbook_proto_depIdxs = nil
}
