// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: orderbook.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define a Person message
type Orderbook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Buy           []*MatchEngineEntry    `protobuf:"bytes,2,rep,name=buy,proto3" json:"buy,omitempty"`
	Sell          []*MatchEngineEntry    `protobuf:"bytes,3,rep,name=sell,proto3" json:"sell,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Orderbook) Reset() {
	*x = Orderbook{}
	mi := &file_orderbook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Orderbook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Orderbook) ProtoMessage() {}

func (x *Orderbook) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Orderbook.ProtoReflect.Descriptor instead.
func (*Orderbook) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{0}
}

func (x *Orderbook) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Orderbook) GetBuy() []*MatchEngineEntry {
	if x != nil {
		return x.Buy
	}
	return nil
}

func (x *Orderbook) GetSell() []*MatchEngineEntry {
	if x != nil {
		return x.Sell
	}
	return nil
}

type MatchEngineEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         string                 `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Orders        []*Order               `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchEngineEntry) Reset() {
	*x = MatchEngineEntry{}
	mi := &file_orderbook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchEngineEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchEngineEntry) ProtoMessage() {}

func (x *MatchEngineEntry) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchEngineEntry.ProtoReflect.Descriptor instead.
func (*MatchEngineEntry) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{1}
}

func (x *MatchEngineEntry) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *MatchEngineEntry) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`
	Price         string                 `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Volume        string                 `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_orderbook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_orderbook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_orderbook_proto_rawDescGZIP(), []int{2}
}

func (x *Order) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Order) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *Order) GetVolume() string {
	if x != nil {
		return x.Volume
	}
	return ""
}

var File_orderbook_proto protoreflect.FileDescriptor

const file_orderbook_proto_rawDesc = "" +
	"\n" +
	"\x0forderbook.proto\x12\x06models\"}\n" +
	"\tOrderbook\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12*\n" +
	"\x03buy\x18\x02 \x03(\v2\x18.models.MatchEngineEntryR\x03buy\x12,\n" +
	"\x04sell\x18\x03 \x03(\v2\x18.models.MatchEngineEntryR\x04sell\"O\n" +
	"\x10MatchEngineEntry\x12\x14\n" +
	"\x05price\x18\x01 \x01(\tR\x05price\x12%\n" +
	"\x06orders\x18\x02 \x03(\v2\r.models.OrderR\x06orders\"q\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12\x14\n" +
	"\x05price\x18\x04 \x01(\tR\x05price\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\tR\x06volumeB\n" +
	"Z\b./modelsb\x06proto3"

var (
	file_orderbook_proto_rawDescOnce sync.Once
	file_orderbook_proto_rawDescData []byte
)

func file_orderbook_proto_rawDescGZIP() []byte {
	file_orderbook_proto_rawDescOnce.Do(func() {
		file_orderbook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orderbook_proto_rawDesc), len(file_orderbook_proto_rawDesc)))
	})
	return file_orderbook_proto_rawDescData
}

var file_orderbook_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orderbook_proto_goTypes = []any{
	(*Orderbook)(nil),        // 0: models.Orderbook
	(*MatchEngineEntry)(nil), // 1: models.MatchEngineEntry
	(*Order)(nil),            // 2: models.Order
}
var file_orderbook_proto_depIdxs = []int32{
	1, // 0: models.Orderbook.buy:type_name -> models.MatchEngineEntry
	1, // 1: models.Orderbook.sell:type_name -> models.MatchEngineEntry
	2, // 2: models.MatchEngineEntry.orders:type_name -> models.Order
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_orderbook_proto_init() }
func file_orderbook_proto_init() {
	if File_orderbook_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orderbook_proto_rawDesc), len(file_orderbook_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orderbook_proto_goTypes,
		DependencyIndexes: file_orderbook_proto_depIdxs,
		MessageInfos:      file_orderbook_proto_msgTypes,
	}.Build()
	File_orderbook_proto = out.File
	file_orderbook_proto_goTypes = nil
	file_orderbook_proto_depIdxs = nil
}
